#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit facebook youtube weather apps cava mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--gc" ]]; then
	close_dash && google-chrome-stable &

elif [[ "$1" == "--subl" ]]; then
	close_dash && subl&

elif [[ "$1" == "--dc" ]]; then
	close_dash && discord &

elif [[ "$1" == "--telegram" ]]; then
	close_dash && telegram-desktop &

elif [[ "$1" == "--code" ]]; then
	close_dash && code &

elif [[ "$1" == "--github" ]]; then
	close_dash && github-desktop &

fi
